[build]
  base = "/"
  publish = "public/"
  command = "npm run build"
  node_version = "16"
  functions = "functions/"
[dev]
  publish = "public"
[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200